name: Sync Submodules
on: workflow_dispatch
jobs:

  repo_sync:
    name: Sync with Main repo
    runs-on: ubuntu-latest
    steps:
    - name: ssh and git module update
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /opt/software-discovery-tool-deploy
          git checkout -b "$(date +%b%d)"
          git pull --recurse-submodules origin main
          git submodule update --remote --recursive
          git remote add update https://${{ secrets.SDT_USER_PUSH }}:{{ secrets.SDT_PAT_PUSH }}@github.com/openmainframeproject/software-discovery-tool-deploy.git
          git commit -sam "Auto updated submodule references" && git push update "$(date +%b%d)" || echo "No changes to commit"
